// ==========================================
// 1. LÓGICA DEL CARRUSEL (HERO)
// ==========================================
let currentSlide = 0;

function showSlide(index) {
    const slides = document.querySelectorAll('.slide');
    if (slides.length === 0) return;

    slides.forEach(slide => slide.classList.remove('active'));
    currentSlide = (index + slides.length) % slides.length;
    slides[currentSlide].classList.add('active');
}

function moveSlide(step) {
    showSlide(currentSlide + step);
}

let slideInterval = setInterval(() => {
    moveSlide(1);
}, 5000);

function manualMove(step) {
    clearInterval(slideInterval);
    moveSlide(step);
    slideInterval = setInterval(() => {
        moveSlide(1);
    }, 5000);
}

// ==========================================
// 2. DICCIONARIO DE TRADUCCIONES (ACTUALIZADO)
// ==========================================
const translations = {
    'es': {
        'nav_home': 'INICIO',
        'nav_about': 'Sobre nosotros',
        'nav_areas': 'Areas',
        'nav_premios': 'Blog',
        'nav_contact': 'Contacto',
        'hero_title': 'CICTAEC',
        'hero_subtitle': 'Cámara Internacional de Comercio y Turismo',
        'hero_slide_connect': 'CONECTANDO CONTINENTES',
        'hero_slide_bridge': 'TU PUENTE AL MUNDO',
        'hero_slide_3': 'CICTAEC',
        'about_title': 'Cámara Internacional de Comercio y Turismo Asociación Ecuatoriano-Catalán',
        'about_description': 'CICTAEC es una organización de carácter internacional que actúa como puente entre latinoamérica y Europa, promocionando y facilitando relaciones comerciales y turísticas. La entidad trabaja en la promoción de la exportación de productos de calidad como banano, trucha y miel, mostrando así la diversidad económica y la generación de oportunidades internacionales de negocio.',
        'founder_tag': 'SOBRE CICTAEC',
        'founder_quote': '"CICTAEC es una organización de carácter internacional que actúa como puente entre latinoamérica<br>y Europa, promocionando y facilitando relaciones comerciales y turísticas."',
        'founder_title': 'FUNDADORA',
        'mission_title': 'Misión',
        'mission_text': 'Ser un puente eficaz en la conexión internacional entre Ecuador y Europa, promoviendo relaciones comerciales, facilitando oportunidades de negocios e involucrando instituciones públicas y privadas de ambos continentes.',
        'vision_title': 'Visión',
        'vision_text': 'Ser una cámara de referencia en la conexión internacional entre Ecuador y Europa, relacionando sectores de importancia tales como comercio, turismo, educación, innovación tecnológica, industrial y agrícola, promocionando la exportación de productos de calidad y creando oportunidades de desarrollo económico y empresarial.',
        'areas_main_title': 'AREAS',
        'area_1': 'COMERCIO',
        'area_2': 'CULTURA Y TURISMO',
        'area_3': 'DEPORTE',
        'commerce_title': 'COMERCIO',
        'trad_prod_title': 'PRODUCTOS TRADICIONALES',
        'trad_prod_desc': 'Conectamos los mercados',
        'btn_more': 'VER MAS DETALLES',
        'btn_info': 'SOLICITAR INFO',
        'btn_advisory': 'SOLICITAR ASESORÍA',
        'btn_details': 'DETALLES',
        'btn_details_area': 'IR A LA SECCIÓN',
        'btn_form': 'FORMULARIO DE CONTACTO',
        'ie_title': 'IMPORTACIÓN & EXPORTACIÓN',
        'ie_desc': 'Facilitamos los procesos logisticos',
        'products_section_title': 'PRODUCTOS',
        'catalog_section_title': 'CATALOGO',
        'btn_view_products': 'VER PRODUCTOS',
        'tourism_subtitle': 'TURISMO',
        'tourism_desc': 'Impulsamos el turismo sostenible y el reconocimiento de destinos estratégicos en ambos continentes, facilitando el intercambio cultural.',
        'cultural_subtitle': 'CULTURA',
        'cultural_desc': 'Preservamos y difundimos las tradiciones y el arte del Ecuador. La cultura es nuestra fuerza para unir comunidades e impulsar el desarollo.',
        'sport_subtitle': 'PROMOVEMOS DEPORTE',
        'sport_desc': 'Fomentamos el intercambio deportivo y la promoción de eventos deportivos entre Ecuador y Europa, creando oportunidades de desarrollo en el ámbito deportivo internacional.',
        'sport_page_title': 'DEPORTE',
        'sport_clubs_title': 'CLUBES ASOCIADOS',
        'club1_name': 'BEISBOL4ALL',
        'club1_desc': 'Club especializado en béisbol con programas de desarrollo para jóvenes atletas. Fomenta el intercambio deportivo y la formación de talento en el béisbol español.',
        'club2_name': 'PENYA',
        'club2_desc': 'Club deportivo catalán con tradición en múltiples disciplinas. Enfocado en la promoción del deporte base y la cooperación internacional con clubes de América Latina.',
        'btn_visit_website': 'Visitar sitio web',
        'sport_exchanges_title': 'INTERCAMBIOS DEPORTIVOS',
        'sport_exchanges_desc': 'Facilitamos el intercambio de atletas, entrenadores y profesionales del deporte entre Ecuador y Europa, promoviendo la cooperación deportiva internacional y el desarrollo de talento.',
        'sport_exchanges_item1': 'Programas de intercambio para atletas',
        'sport_exchanges_item2': 'Formación de entrenadores',
        'sport_exchanges_item3': 'Cooperación técnica deportiva',
        'sport_events_title': 'EVENTOS DEPORTIVOS',
        'sport_events_desc': 'Organizamos y promocionamos eventos deportivos que conectan a Ecuador con Europa, creando oportunidades para la participación internacional y el desarrollo del deporte.',
        'sport_events_item1': 'Torneos internacionales',
        'sport_events_item2': 'Competencias bilaterales',
        'sport_events_item3': 'Eventos deportivos culturales',
        'sport_infrastructure_title': 'INFRAESTRUCTURA DEPORTIVA',
        'sport_infrastructure_desc': 'Apoyamos el desarrollo de infraestructura deportiva y la transferencia de conocimientos técnicos para mejorar las instalaciones y condiciones de entrenamiento.',
        'sport_infrastructure_item1': 'Consultoría en instalaciones deportivas',
        'sport_infrastructure_item2': 'Equipamiento deportivo de calidad',
        'sport_infrastructure_item3': 'Asesoría técnica especializada',
        'sport_business_title': 'NEGOCIOS DEPORTIVOS',
        'sport_business_desc': 'Facilitamos conexiones comerciales en el sector deportivo, incluyendo patrocinios, marketing deportivo y oportunidades de inversión en el ámbito deportivo internacional.',
        'sport_business_item1': 'Conexión con patrocinadores',
        'sport_business_item2': 'Marketing deportivo internacional',
        'sport_business_item3': 'Oportunidades de inversión',
        'sport_contact_title': '¿INTERESADO EN COLABORAR?',
        'sport_contact_desc': 'Si deseas participar en nuestros programas deportivos o tienes una propuesta de colaboración, no dudes en contactarnos.',
        'btn_contact': 'CONTACTAR',
        'btn_back_home': 'Volver al inicio',
        'contact_company_name': 'Cámara Internacional de Comercio y Turismo',
        'contact_section_title': 'CONTACTO',
        'address_label': 'Dirección:',
        'phone_label': 'Teléfono:',
        'footer_copy': '© 2026 CICTAEC - Cámara Internacional de Comercio y Turismo. Todos los derechos reservados.',
        'prod_1_title': 'ACEITE',
        'prod_2_title': 'FRUTOS',
        'prod_3_title': 'TEXTIL',
        'prod_4_title': 'JAMON',
        'prod_5_title': 'PESCADO',
        'prod_6_title': 'CACAO',
        'prod_7_title': 'BEBIDAS ALCOHÓLICAS',
        'prod_8_title': 'CEREALES',
        'prod_9_title': 'LEGUMBRES',
        'prod_harina_title': 'HARINA',
        'prod_harina_desc': 'Harina de trigo de alta calidad para la industria panadera y pastelera, ideal para exportación internacional.',
        'prod_pasta_title': 'PASTA',
        'prod_pasta_desc': 'Pasta italiana de alta calidad elaborada con trigo duro, perfecta para la gastronomía internacional y exportación.',
        'prod_patatas_fritas_title': 'PATATAS FRITAS',
        'prod_patatas_fritas_desc': 'Patatas fritas crujientes de calidad superior, elaboradas con las mejores patatas europeas para exportación.',
        'prod_papas_dauphine_title': 'PAPAS DAUPHINE',
        'prod_papas_dauphine_desc': 'Papas dauphine de cocina francesa, mezcla perfecta de puré de patata y pasta choux, listas para exportación.',
        'prod_vino_title': 'VINO',
        'prod_vino_desc': 'Vinos selectos de alta calidad, ideales para exportación a mercados internacionales exigentes.',
        'prod_champagne_title': 'CHAMPAGNE',
        'prod_champagne_desc': 'Champagne premium de origen europeo, perfecto para celebraciones y eventos especiales de lujo.',
        'prod_1_desc': 'Aceite de alta calidad proveniente de Ecuador, ideal para exportación a mercados internacionales.',
        'prod_2_desc': 'Frutas frescas y frutos secos de la mejor calidad, cultivados en las tierras ecuatorianas.',
        'prod_aceite_oliva_intenso': 'ACEITE OLIVA INTENSO',
        'prod_aceite_oliva_intenso_desc': 'Aceite de oliva intenso de alta calidad, ideal para exportación a mercados internacionales.',
        'prod_3_desc': 'Productos textiles artesanales y de alta calidad, representando la tradición ecuatoriana.',
        'prod_banana_title': 'BANANO',
        'prod_banana_desc': 'Banano ecuatoriano de exportación, reconocido mundialmente por su sabor dulce y textura perfecta.',
        'prod_pitaya_title': 'PITAYA',
        'prod_pitaya_desc': 'Pitaya o fruta del dragón, exótica y nutritiva, cultivada en las tierras tropicales de Ecuador.',
        'prod_4_desc': 'Jamón curado de excelente calidad, preparado con métodos tradicionales.',
        'prod_5_desc': 'Pescado fresco y mariscos de las costas del Pacífico ecuatoriano.',
        'prod_6_desc': 'Cacao ecuatoriano de fino aroma, reconocido mundialmente por su calidad excepcional y sabor único.',
        'prod_atun_title': 'ATUN',
        'prod_atun_desc': 'Atún fresco de las costas del Pacífico ecuatoriano, ideal para la gastronomía internacional.',
        'prod_camaron_title': 'CAMARON',
        'prod_camaron_desc': 'Camarón ecuatoriano de primera calidad, reconocido por su sabor y frescura excepcionales.',
        'prod_albacora_title': 'ALBACORA',
        'prod_albacora_desc': 'Albacora de aguas profundas del Pacífico, apreciada por su textura firme y sabor delicado.',
        'prod_aceite_virgen': 'ACEITE VIRGEN EXTRA',
        'prod_aceite_virgen_desc': 'Aceite virgen extra de primera prensada en frío, con certificación de calidad premium para mercados internacionales.',
        'products_page_title': 'Nuestros Productos',
        'badge_export': 'Exportación',
        'badge_import': 'Importación',
        'error_title': 'Página no encontrada',
        'error_message': 'Lo sentimos, la página que buscas no existe o ha sido movida. Te invitamos a volver a la página principal o explorar nuestros productos y servicios.',
        'error_btn_home': 'Volver al inicio',
        'error_btn_products': 'Ver productos',
        // COOKIES PAGE
        'cookies_title': 'Política de Cookies',
        'cookies_intro': 'Este sitio web utiliza cookies técnicas necesarias para su funcionamiento y mejorar la experiencia de navegación del usuario.',
        'cookies_what_title': '¿Qué son las cookies?',
        'cookies_what_desc': 'Las cookies son pequeños archivos de texto que se almacenan en el navegador del usuario cuando visita un sitio web. Permiten que el sitio recuerde información sobre su visita, como su idioma preferido y otras opciones, lo que puede facilitar su próxima visita y hacer que el sitio le resulte más útil.',
        'cookies_types_title': 'Tipos de cookies que utilizamos',
        'cookies_technical_title': 'Cookies técnicas (necesarias)',
        'cookies_technical_desc': 'Son imprescindibles para el correcto funcionamiento del sitio web. Permiten la navegación y el uso de las diferentes opciones o servicios que ofrece.',
        'cookies_preference_title': 'Cookies de preferencias',
        'cookies_preference_desc': 'Permiten recordar información para que el usuario acceda al servicio con determinadas características, como el idioma seleccionado.',
        'cookies_manage_title': 'Gestión de cookies',
        'cookies_manage_desc': 'El usuario puede configurar su navegador para aceptar o rechazar cookies. La mayoría de los navegadores aceptan cookies automáticamente, pero puede modificar esta configuración. Sin embargo, si decide desactivar las cookies, es posible que algunas funcionalidades del sitio no estén disponibles.',
        'cookies_browsers_title': 'Cómo gestionar cookies en los principales navegadores:',
        'cookies_contact_title': 'Contacto',
        'cookies_contact_desc': 'Para cualquier consulta sobre nuestra política de cookies, puede contactarnos en:',
        // PREMIO/BLOG PAGE
        'premio_page_title': 'Blog - CICTAEC',
        'premio_period_title': 'Período',
        'premio_award': 'Premio',
        'premio_news': 'Noticia',
        'cookies_back_btn': '← Volver al inicio',
        // PRIVACY PAGE
        'privacy_title': 'Política de Privacidad',
        'privacy_intro': 'En cumplimiento del Reglamento General de Protección de Datos (RGPD) y la Ley Orgánica de Protección de Datos (LOPD), le informamos sobre el tratamiento de sus datos personales.',
        'privacy_responsible_title': 'Responsable del tratamiento',
        'privacy_responsible_name': 'Responsable',
        'privacy_data_title': 'Datos personales recogidos',
        'privacy_data_desc': 'A través de los formularios de contacto de nuestro sitio web, podemos recopilar los siguientes datos personales:',
        'privacy_data_name': 'Nombre y apellidos',
        'privacy_data_email': 'Dirección de correo electrónico',
        'privacy_data_phone': 'Teléfono de contacto',
        'privacy_data_company': 'Empresa u organización',
        'privacy_data_message': 'Mensaje o consulta',
        'privacy_purpose_title': 'Finalidad del tratamiento',
        'privacy_purpose_desc': 'Los datos personales proporcionados serán utilizados para:',
        'privacy_purpose_1': 'Responder a sus consultas y solicitudes de información',
        'privacy_purpose_2': 'Proporcionar servicios de asesoramiento comercial y turístico',
        'privacy_purpose_3': 'Enviar información sobre nuestros servicios y actividades (con su consentimiento previo)',
        'privacy_purpose_4': 'Cumplir con obligaciones legales y contractuales',
        'privacy_legal_title': 'Base legal',
        'privacy_legal_desc': 'El tratamiento de sus datos personales se basa en su consentimiento expreso al utilizar nuestros formularios de contacto y en la ejecución de un contrato o medidas precontractuales solicitadas por usted.',
        'privacy_conservation_title': 'Conservación de datos',
        'privacy_conservation_desc': 'Sus datos personales serán conservados durante el tiempo necesario para cumplir con la finalidad para la que fueron recabados y, posteriormente, durante el periodo de prescripción de las obligaciones legales aplicables.',
        'privacy_rights_title': 'Derechos del usuario',
        'privacy_rights_desc': 'Usted tiene derecho a:',
        'privacy_rights_1': 'Acceso: Obtener información sobre si estamos tratando sus datos personales',
        'privacy_rights_2': 'Rectificación: Solicitar la corrección de datos inexactos o incompletos',
        'privacy_rights_3': 'Supresión: Solicitar la eliminación de sus datos personales',
        'privacy_rights_4': 'Limitación: Solicitar la limitación del tratamiento de sus datos',
        'privacy_rights_5': 'Portabilidad: Recibir sus datos en un formato estructurado y de uso común',
        'privacy_rights_6': 'Oposición: Oponerse al tratamiento de sus datos personales',
        'privacy_rights_access': 'Acceso',
        'privacy_rights_rectification': 'Rectificación',
        'privacy_rights_deletion': 'Supresión',
        'privacy_rights_limitation': 'Limitación',
        'privacy_rights_portability': 'Portabilidad',
        'privacy_rights_opposition': 'Oposición',
        'privacy_rights_exercise': 'Para ejercer estos derechos, puede contactarnos en info@cictaec.es o en el +34 664 413 231.',
        'privacy_security_title': 'Seguridad de los datos',
        'privacy_security_desc': 'CICTAEC ha adoptado las medidas técnicas y organizativas necesarias para garantizar la seguridad e integridad de los datos personales, así como para evitar su pérdida, alteración o acceso no autorizado.',
        'privacy_changes_title': 'Modificaciones de la política',
        'privacy_changes_desc': 'CICTAEC se reserva el derecho de modificar esta política de privacidad para adaptarla a cambios legislativos o jurisprudenciales. Le recomendamos revisar periódicamente esta página para estar informado de cualquier cambio.',
        'privacy_back_btn': '← Volver al inicio',
        'form_url': 'https://forms.gle/5951nVBJNCh4sBi78'
    },
    'fr': {
        'nav_home': 'ACCUEIL',
        'nav_about': 'À propos',
        'nav_areas': 'Domaines',
        'nav_premios': 'Blog',
        'nav_contact': 'Contact',
        'hero_title': 'CICTAEC',
        'hero_subtitle': 'Chambre Internationale de Commerce et de Tourisme',
        'hero_slide_connect': 'CONNECTER LES CONTINENTS',
        'hero_slide_bridge': 'VOTRE PONT VERS LE MONDE',
        'hero_slide_3': 'CICTAEC',
        'about_title': 'Chambre Internationale de Commerce et de Tourisme Association Équatoriano-Catalane',
        'about_description': 'CICTAEC est une organisation internationale qui agit comme un pont entre l\'Amérique latine et l\'Europe, promouvant et facilitant les relations commerciales et touristiques. L\'entité travaille à la promotion de l\'exportation de produits de qualité comme les bananes, la truite et le miel.',
        'founder_tag': 'À PROPOS DE CICTAEC',
        'founder_quote': '"CICTAEC est une organisation internationale agissant comme un pont entre l\'Amérique latine<br>et l\'Europe, promouvant les relations commerciales et touristiques."',
        'founder_title': 'FONDATRICE',
        'mission_title': 'Mission',
        'mission_text': 'Être un pont efficace dans la connexion internationale entre l\'Équateur et l\'Europe, en promouvant les relations commerciales, en facilitant les opportunités d\'affaires et en impliquant les institutions publiques et privées des deux continents.',
        'vision_title': 'Vision',
        'vision_text': 'Être une chambre de référence dans la connexion internationale entre l\'Équateur et l\'Europe, reliant des secteurs d\'importance tels que le commerce, le tourisme, l\'éducation, l\'innovation technologique, industrielle et agricole.',
        'areas_main_title': 'DOMAINES',
        'area_1': 'COMMERCE',
        'area_2': 'CULTURE ET TOURISME',
        'area_3': 'SPORT',
        'commerce_title': 'COMMERCE',
        'trad_prod_title': 'PRODUITS TRADITIONNELS',
        'trad_prod_desc': 'Nous connectons les marchés',
        'btn_more': 'VOIR PLUS DE DÉTAILS',
        'btn_info': 'DEMANDER INFO',
        'btn_advisory': 'DEMANDER CONSEIL',
        'btn_details': 'DÉTAILS',        'btn_details_area': 'ALLER À LA SECTION',        'btn_form': 'FORMULAIRE DE CONTACT',
        'ie_title': 'IMPORTATION & EXPORTATION',
        'ie_desc': 'Nous facilitons les processus logistiques',
        'products_section_title': 'PRODUITS',
        'catalog_section_title': 'CATALOGUE',
        'btn_view_products': 'VOIR LES PRODUITS',
        'tourism_subtitle': 'TOURISME',
        'tourism_desc': 'Nous promouvons le tourisme durable et la reconnaissance des destinations stratégiques sur les deux continents.',
        'cultural_subtitle': 'CULTURE',
        'cultural_desc': 'Nous préservons et diffusons les traditions et l\'art de l\'Équateur. La culture est notre force pour unir les communautés et stimuler le développement.',
        'sport_subtitle': 'NOUS PROMOUVONS LE SPORT',
        'sport_desc': 'Nous encourageons les échanges sportifs et la promotion d\'événements sportifs entre l\'Équateur et l\'Europe, créant des opportunités de développement dans le domaine sportif international.',
        'sport_page_title': 'SPORT',
        'sport_clubs_title': 'CLUBS ASSOCIÉS',
        'club1_name': 'BEISBOL4ALL',
        'club1_desc': 'Club spécialisé en baseball avec des programmes de développement pour jeunes athlètes. Favorise les échanges sportifs et la formation de talents dans le baseball espagnol.',
        'club2_name': 'PENYA',
        'club2_desc': 'Club sportif catalan avec une tradition dans plusieurs disciplines. Axé sur la promotion du sport de base et la coopération internationale avec les clubs d\'Amérique latine.',
        'btn_visit_website': 'Visiter le site web',
        'sport_exchanges_title': 'ÉCHANGES SPORTIFS',
        'sport_exchanges_desc': 'Nous facilitons les échanges d\'athlètes, d\'entraîneurs et de professionnels du sport entre l\'Équateur et l\'Europe, en promouvant la coopération sportive internationale et le développement des talents.',
        'sport_exchanges_item1': 'Programmes d\'échange pour athlètes',
        'sport_exchanges_item2': 'Formation d\'entraîneurs',
        'sport_exchanges_item3': 'Coopération technique sportive',
        'sport_events_title': 'ÉVÉNEMENTS SPORTIFS',
        'sport_events_desc': 'Nous organisons et promouvons des événements sportifs qui relient l\'Équateur à l\'Europe, créant des opportunités de participation internationale et de développement du sport.',
        'sport_events_item1': 'Tournois internationaux',
        'sport_events_item2': 'Compétitions bilatérales',
        'sport_events_item3': 'Événements sportifs culturels',
        'sport_infrastructure_title': 'INFRASTRUCTURE SPORTIVE',
        'sport_infrastructure_desc': 'Nous soutenons le développement d\'infrastructures sportives et le transfert de connaissances techniques pour améliorer les installations et les conditions d\'entraînement.',
        'sport_infrastructure_item1': 'Conseil en installations sportives',
        'sport_infrastructure_item2': 'Équipement sportif de qualité',
        'sport_infrastructure_item3': 'Conseil technique spécialisé',
        'sport_business_title': 'AFFAIRES SPORTIVES',
        'sport_business_desc': 'Nous facilitons les connexions commerciales dans le secteur sportif, y compris les parrainages, le marketing sportif et les opportunités d\'investissement dans le domaine sportif international.',
        'sport_business_item1': 'Connexion avec les sponsors',
        'sport_business_item2': 'Marketing sportif international',
        'sport_business_item3': 'Opportunités d\'investissement',
        'sport_contact_title': 'INTÉRESSÉ À COLLABORER?',
        'sport_contact_desc': 'Si vous souhaitez participer à nos programmes sportifs ou avez une proposition de collaboration, n\'hésitez pas à nous contacter.',
        'btn_contact': 'CONTACTER',
        'btn_back_home': 'Retour à l\'accueil',
        'contact_company_name': 'Chambre Internationale de Commerce et de Tourisme',
        'contact_section_title': 'CONTACT',
        'address_label': 'Adresse:',
        'phone_label': 'Téléphone:',
        'footer_copy': '© 2026 CICTAEC - Chambre Internationale de Commerce et de Tourisme. Tous droits réservés.',
        'prod_1_title': 'HUILE',
        'prod_2_title': 'FRUITS',
        'prod_3_title': 'TEXTILE',
        'prod_4_title': 'JAMBON',
        'prod_5_title': 'POISSON',        'prod_6_title': 'CACAO',        'prod_7_title': 'BOISSONS ALCOOLISÉES',
        'prod_8_title': 'CÉRÉALES',
        'prod_9_title': 'LÉGUMES',
        'prod_harina_title': 'FARINE',
        'prod_harina_desc': 'Farine de blé de haute qualité pour l\'industrie de la boulangerie et de la pâtisserie, idéale pour l\'exportation internationale.',
        'prod_pasta_title': 'PÂTES',
        'prod_pasta_desc': 'Pâtes italiennes de haute qualité élaborées avec du blé dur, parfaites pour la gastronomie internationale et l\'exportation.',
        'prod_patatas_fritas_title': 'FRITES',
        'prod_patatas_fritas_desc': 'Frites croustillantes de qualité supérieure, élaborées avec les meilleures pommes de terre européennes pour l\'exportation.',
        'prod_papas_dauphine_title': 'POMMES DAUPHINE',
        'prod_papas_dauphine_desc': 'Pommes dauphine de cuisine française, mélange parfait de purée de pommes de terre et de pâte à choux, prêtes pour l\'exportation.',
        'prod_vino_title': 'VIN',
        'prod_vino_desc': 'Vins sélectionnés de haute qualité, idéaux pour l\'exportation vers des marchés internationaux exigeants.',
        'prod_champagne_title': 'CHAMPAGNE',
        'prod_champagne_desc': 'Champagne premium d\'origine européenne, parfait pour les célébrations et événements spéciaux de luxe.',
        'prod_1_desc': 'Huile de haute qualité provenant d\'Équateur, idéale pour l\'exportation vers les marchés internationaux.',
        'prod_2_desc': 'Fruits frais et fruits secs de la meilleure qualité, cultivés sur les terres équatoriennes.',
        'prod_aceite_oliva_intenso': 'HUILE D\'OLIVE INTENSE',
        'prod_aceite_oliva_intenso_desc': 'Huile d\'olive intense de haute qualité, idéale pour l\'exportation vers les marchés internationaux.',
        'prod_3_desc': 'Produits textiles artisanaux de haute qualité, représentant la tradition équatorienne.',
        'prod_banana_title': 'BANANE',
        'prod_banana_desc': 'Banane équatorienne d\'exportation, reconnue mondialement pour sa saveur sucrée et sa texture parfaite.',
        'prod_pitaya_title': 'PITAYA',
        'prod_pitaya_desc': 'Pitaya ou fruit du dragon, exotique et nutritif, cultivé dans les terres tropicales de l\'\u00c9quateur.',
        'prod_4_desc': 'Jambon séché de qualité exceptionnelle, préparé selon des méthodes traditionnelles.',
        'prod_5_desc': 'Poissons frais et fruits de mer des côtes du Pacifique équatorien.',
        'prod_6_desc': 'Cacao équatorien à arôme fin, reconnu mondialement pour sa qualité exceptionnelle et sa saveur unique.',
        'prod_atun_title': 'THON',
        'prod_atun_desc': 'Thon frais des côtes du Pacifique équatorien, idéal pour la gastronomie internationale.',
        'prod_camaron_title': 'CREVETTE',
        'prod_camaron_desc': 'Crevette équatorienne de première qualité, reconnue pour sa saveur et sa fraîcheur exceptionnelles.',
        'prod_albacora_title': 'ALBACORE',
        'prod_albacora_desc': 'Albacore des eaux profondes du Pacifique, apprécié pour sa texture ferme et sa saveur délicate.',        'prod_aceite_virgen': 'HUILE VIERGE EXTRA',
        'prod_aceite_virgen_desc': 'Huile vierge extra de première pression à froid, avec certification de qualité premium pour les marchés internationaux.',        'products_page_title': 'Nos Produits',
        'badge_export': 'Exportation',
        'badge_import': 'Importation',
        'error_title': 'Page non trouvée',
        'error_message': 'Désolé, la page que vous recherchez n\'existe pas ou a été déplacée. Nous vous invitons à retourner à la page principale ou à explorer nos produits et services.',
        'error_btn_home': 'Retour à l\'accueil',
        'error_btn_products': 'Voir les produits',
        // COOKIES PAGE
        'cookies_title': 'Politique de Cookies',
        'cookies_intro': 'Ce site web utilise des cookies techniques nécessaires à son fonctionnement et pour améliorer l\'expérience de navigation de l\'utilisateur.',
        'cookies_what_title': 'Que sont les cookies?',
        'cookies_what_desc': 'Les cookies sont de petits fichiers texte stockés dans le navigateur de l\'utilisateur lors de la visite d\'un site web. Ils permettent au site de mémoriser des informations sur votre visite, comme votre langue préférée et d\'autres options, ce qui peut faciliter votre prochaine visite et rendre le site plus utile.',
        'cookies_types_title': 'Types de cookies que nous utilisons',
        'cookies_technical_title': 'Cookies techniques (nécessaires)',
        'cookies_technical_desc': 'Ils sont essentiels au bon fonctionnement du site web. Ils permettent la navigation et l\'utilisation des différentes options ou services offerts.',
        'cookies_preference_title': 'Cookies de préférences',
        'cookies_preference_desc': 'Permettent de mémoriser des informations pour que l\'utilisateur accède au service avec certaines caractéristiques, comme la langue sélectionnée.',
        'cookies_manage_title': 'Gestion des cookies',
        'cookies_manage_desc': 'L\'utilisateur peut configurer son navigateur pour accepter ou refuser les cookies. La plupart des navigateurs acceptent automatiquement les cookies, mais vous pouvez modifier ce paramètre. Cependant, si vous décidez de désactiver les cookies, il est possible que certaines fonctionnalités du site ne soient pas disponibles.',
        'cookies_browsers_title': 'Comment gérer les cookies dans les principaux navigateurs:',
        'cookies_contact_title': 'Contact',
        'cookies_contact_desc': 'Pour toute question concernant notre politique de cookies, vous pouvez nous contacter à:',
        // PREMIO/BLOG PAGE
        'premio_page_title': 'Blog - CICTAEC',
        'premio_period_title': 'Période',
        'premio_award': 'Prix',
        'premio_news': 'Actualité',
        'cookies_back_btn': '← Retour à l\'accueil',
        // PRIVACY PAGE
        'privacy_title': 'Politique de Confidentialité',
        'privacy_intro': 'Conformément au Règlement Général sur la Protection des Données (RGPD) et à la Loi Organique sur la Protection des Données (LOPD), nous vous informons sur le traitement de vos données personnelles.',
        'privacy_responsible_title': 'Responsable du traitement',
        'privacy_responsible_name': 'Responsable',
        'privacy_data_title': 'Données personnelles collectées',
        'privacy_data_desc': 'Via les formulaires de contact de notre site web, nous pouvons collecter les données personnelles suivantes:',
        'privacy_data_name': 'Nom et prénom',
        'privacy_data_email': 'Adresse e-mail',
        'privacy_data_phone': 'Téléphone de contact',
        'privacy_data_company': 'Entreprise ou organisation',
        'privacy_data_message': 'Message ou demande',
        'privacy_purpose_title': 'Finalité du traitement',
        'privacy_purpose_desc': 'Les données personnelles fournies seront utilisées pour:',
        'privacy_purpose_1': 'Répondre à vos questions et demandes d\'information',
        'privacy_purpose_2': 'Fournir des services de conseil commercial et touristique',
        'privacy_purpose_3': 'Envoyer des informations sur nos services et activités (avec votre consentement préalable)',
        'privacy_purpose_4': 'Respecter les obligations légales et contractuelles',
        'privacy_legal_title': 'Base légale',
        'privacy_legal_desc': 'Le traitement de vos données personnelles repose sur votre consentement explicite lors de l\'utilisation de nos formulaires de contact et sur l\'exécution d\'un contrat ou de mesures précontractuelles demandées par vous.',
        'privacy_conservation_title': 'Conservation des données',
        'privacy_conservation_desc': 'Vos données personnelles seront conservées pendant le temps nécessaire pour remplir la finalité pour laquelle elles ont été collectées et, par la suite, pendant la période de prescription des obligations légales applicables.',
        'privacy_rights_title': 'Droits de l\'utilisateur',
        'privacy_rights_desc': 'Vous avez le droit de:',
        'privacy_rights_1': 'Accès: Obtenir des informations sur le traitement de vos données personnelles',
        'privacy_rights_2': 'Rectification: Demander la correction de données inexactes ou incomplètes',
        'privacy_rights_3': 'Suppression: Demander la suppression de vos données personnelles',
        'privacy_rights_4': 'Limitation: Demander la limitation du traitement de vos données',
        'privacy_rights_5': 'Portabilité: Recevoir vos données dans un format structuré et d\'usage courant',
        'privacy_rights_6': 'Opposition: Vous opposer au traitement de vos données personnelles',
        'privacy_rights_access': 'Accès',
        'privacy_rights_rectification': 'Rectification',
        'privacy_rights_deletion': 'Suppression',
        'privacy_rights_limitation': 'Limitation',
        'privacy_rights_portability': 'Portabilité',
        'privacy_rights_opposition': 'Opposition',
        'privacy_rights_exercise': 'Pour exercer ces droits, vous pouvez nous contacter à info@cictaec.es ou au +34 664 413 231.',
        'privacy_security_title': 'Sécurité des données',
        'privacy_security_desc': 'CICTAEC a adopté les mesures techniques et organisationnelles nécessaires pour garantir la sécurité et l\'intégrité des données personnelles, ainsi que pour éviter leur perte, altération ou accès non autorisé.',
        'privacy_changes_title': 'Modifications de la politique',
        'privacy_changes_desc': 'CICTAEC se réserve le droit de modifier cette politique de confidentialité pour l\'adapter aux changements législatifs ou jurisprudentiels. Nous vous recommandons de consulter régulièrement cette page pour être informé de tout changement.',
        'privacy_back_btn': '← Retour à l\'accueil',
        'form_url': 'https://docs.google.com/forms/d/1Bsjxey6_Y9yGgwF3xPTHx7tOudQXe6t5cxqrB5cBO5E/viewform'
    },
    'en': {
        'nav_home': 'HOME',
        'nav_about': 'About Us',
        'nav_areas': 'Areas',
        'nav_premios': 'Blog',
        'nav_contact': 'Contact',
        'hero_title': 'CICTAEC',
        'hero_subtitle': 'International Chamber of Commerce and Tourism',
        'hero_slide_connect': 'CONNECTING CONTINENTS',
        'hero_slide_bridge': 'YOUR BRIDGE TO THE WORLD',
        'hero_slide_3': 'CICTAEC',
        'about_title': 'International Chamber of Commerce and Tourism Ecuadorian-Catalan Association',
        'about_description': 'CICTAEC is an international organization acting as a bridge between Latin America and Europe, promoting and facilitating commercial and tourist relations.',
        'founder_tag': 'ABOUT CICTAEC',
        'founder_quote': '"CICTAEC is an international organization acting as a bridge between Latin America<br>and Europe."',
        'founder_title': 'FOUNDER',
        'mission_title': 'Mission',
        'mission_text': 'To be an effective bridge in the international connection between Ecuador and Europe, promoting trade relations and business opportunities.',
        'vision_title': 'Vision',
        'vision_text': 'To be a reference chamber in the international connection between Ecuador and Europe, relating important sectors such as trade, tourism, education, technological innovation, industrial and agricultural.',
        'areas_main_title': 'AREAS',
        'area_1': 'COMMERCE',
        'area_2': 'CULTURE AND TOURISM',
        'area_3': 'SPORT',
        'commerce_title': 'COMMERCE',
        'trad_prod_title': 'TRADITIONAL PRODUCTS',
        'trad_prod_desc': 'We connect markets',
        'btn_more': 'SEE MORE DETAILS',
        'btn_info': 'REQUEST INFO',
        'btn_advisory': 'REQUEST ADVISORY',
        'btn_details': 'DETAILS',
        'btn_details_area': 'GO TO SECTION',
        'btn_form': 'CONTACT FORM',
        'ie_title': 'IMPORT & EXPORT',
        'ie_desc': 'We facilitate logistical processes',
        'products_section_title': 'PRODUCTS',
        'catalog_section_title': 'CATALOG',
        'btn_view_products': 'VIEW PRODUCTS',
        'tourism_subtitle': 'TOURISM',
        'tourism_desc': 'We promote sustainable tourism and the recognition of strategic destinations on both continents.',
        'cultural_subtitle': 'CULTURE',
        'cultural_desc': 'We preserve and disseminate the traditions and art of Ecuador. Culture is our strength to unite communities and drive development.',
        'sport_subtitle': 'WE PROMOTE SPORTS',
        'sport_desc': 'We promote sports exchange and the promotion of sporting events between Ecuador and Europe, creating development opportunities in the international sports field.',
        'sport_page_title': 'SPORTS',
        'sport_clubs_title': 'PARTNER CLUBS',
        'club1_name': 'BEISBOL4ALL',
        'club1_desc': 'Specialized baseball club with development programs for young athletes. Promotes sports exchange and talent formation in Spanish baseball.',
        'club2_name': 'PENYA',
        'club2_desc': 'Catalan sports club with tradition in multiple disciplines. Focused on grassroots sports promotion and international cooperation with Latin American clubs.',
        'btn_visit_website': 'Visit website',
        'sport_exchanges_title': 'SPORTS EXCHANGES',
        'sport_exchanges_desc': 'We facilitate the exchange of athletes, coaches and sports professionals between Ecuador and Europe, promoting international sports cooperation and talent development.',
        'sport_exchanges_item1': 'Exchange programs for athletes',
        'sport_exchanges_item2': 'Coach training',
        'sport_exchanges_item3': 'Sports technical cooperation',
        'sport_events_title': 'SPORTING EVENTS',
        'sport_events_desc': 'We organize and promote sporting events that connect Ecuador with Europe, creating opportunities for international participation and sports development.',
        'sport_events_item1': 'International tournaments',
        'sport_events_item2': 'Bilateral competitions',
        'sport_events_item3': 'Cultural sports events',
        'sport_infrastructure_title': 'SPORTS INFRASTRUCTURE',
        'sport_infrastructure_desc': 'We support the development of sports infrastructure and the transfer of technical knowledge to improve training facilities and conditions.',
        'sport_infrastructure_item1': 'Sports facilities consulting',
        'sport_infrastructure_item2': 'Quality sports equipment',
        'sport_infrastructure_item3': 'Specialized technical advice',
        'sport_business_title': 'SPORTS BUSINESS',
        'sport_business_desc': 'We facilitate commercial connections in the sports sector, including sponsorships, sports marketing and investment opportunities in the international sports field.',
        'sport_business_item1': 'Connection with sponsors',
        'sport_business_item2': 'International sports marketing',
        'sport_business_item3': 'Investment opportunities',
        'sport_contact_title': 'INTERESTED IN COLLABORATING?',
        'sport_contact_desc': 'If you wish to participate in our sports programs or have a collaboration proposal, do not hesitate to contact us.',
        'btn_contact': 'CONTACT',
        'btn_back_home': 'Back to home',
        'contact_company_name': 'International Chamber of Commerce and Tourism',
        'contact_section_title': 'CONTACT',
        'address_label': 'Address:',
        'phone_label': 'Phone:',
        'footer_copy': '© 2026 CICTAEC - International Chamber of Commerce and Tourism. All rights reserved.',
        'prod_1_title': 'OIL',
        'prod_2_title': 'FRUITS',
        'prod_3_title': 'TEXTILE',
        'prod_4_title': 'HAM',
        'prod_5_title': 'FISH',
        'prod_6_title': 'COCOA',
        'prod_7_title': 'ALCOHOLIC BEVERAGES',
        'prod_8_title': 'CEREALS',
        'prod_9_title': 'VEGETABLES',
        'prod_harina_title': 'FLOUR',
        'prod_harina_desc': 'High quality wheat flour for the bakery and pastry industry, ideal for international export.',
        'prod_pasta_title': 'PASTA',
        'prod_pasta_desc': 'High quality Italian pasta made with durum wheat, perfect for international gastronomy and export.',
        'prod_patatas_fritas_title': 'FRENCH FRIES',
        'prod_patatas_fritas_desc': 'Crispy french fries of superior quality, made with the best European potatoes for export.',
        'prod_papas_dauphine_title': 'DAUPHINE POTATOES',
        'prod_papas_dauphine_desc': 'French dauphine potatoes, perfect blend of mashed potatoes and choux pastry, ready for export.',
        'prod_vino_title': 'WINE',
        'prod_vino_desc': 'Select high quality wines, ideal for export to demanding international markets.',
        'prod_champagne_title': 'CHAMPAGNE',
        'prod_champagne_desc': 'Premium champagne of European origin, perfect for celebrations and luxury special events.',
        'prod_1_desc': 'High quality oil from Ecuador, ideal for export to international markets.',
        'prod_2_desc': 'Fresh fruits and dried fruits of the best quality, grown on Ecuadorian lands.',
        'prod_aceite_oliva_intenso': 'INTENSE OLIVE OIL',
        'prod_aceite_oliva_intenso_desc': 'High quality intense olive oil, ideal for export to international markets.',
        'prod_3_desc': 'Handcrafted textile products of high quality, representing Ecuadorian tradition.',
        'prod_banana_title': 'BANANA',
        'prod_banana_desc': 'Export-quality Ecuadorian banana, recognized worldwide for its sweet flavor and perfect texture.',
        'prod_pitaya_title': 'PITAYA',
        'prod_pitaya_desc': 'Pitaya or dragon fruit, exotic and nutritious, grown in the tropical lands of Ecuador.',
        'prod_4_desc': 'Cured ham of excellent quality, prepared with traditional methods.',
        'prod_5_desc': 'Fresh fish and seafood from the Ecuadorian Pacific coast.',
        'prod_6_desc': 'Fine aroma Ecuadorian cocoa, recognized worldwide for its exceptional quality and unique flavor.',
        'prod_atun_title': 'TUNA',
        'prod_atun_desc': 'Fresh tuna from the Ecuadorian Pacific coast, ideal for international gastronomy.',
        'prod_camaron_title': 'SHRIMP',
        'prod_camaron_desc': 'Top quality Ecuadorian shrimp, recognized for its exceptional flavor and freshness.',
        'prod_albacora_title': 'ALBACORE',
        'prod_albacora_desc': 'Deep water Pacific albacore, appreciated for its firm texture and delicate flavor.',
        'prod_aceite_virgen': 'EXTRA VIRGIN OIL',
        'prod_aceite_virgen_desc': 'Extra virgin oil from first cold pressing, with premium quality certification for international markets.',
        'products_page_title': 'Our Products',
        'badge_export': 'Export',
        'badge_import': 'Import',
        'error_title': 'Page not found',
        'error_message': 'Sorry, the page you are looking for does not exist or has been moved. We invite you to return to the main page or explore our products and services.',
        'error_btn_home': 'Back to home',
        'error_btn_products': 'View products',
        // COOKIES PAGE
        'cookies_title': 'Cookie Policy',
        'cookies_intro': 'This website uses technical cookies necessary for its operation and to improve the user browsing experience.',
        'cookies_what_title': 'What are cookies?',
        'cookies_what_desc': 'Cookies are small text files that are stored in the user\'s browser when visiting a website. They allow the site to remember information about your visit, such as your preferred language and other options, which can facilitate your next visit and make the site more useful.',
        'cookies_types_title': 'Types of cookies we use',
        'cookies_technical_title': 'Technical cookies (necessary)',
        'cookies_technical_desc': 'They are essential for the proper functioning of the website. They allow navigation and use of the different options or services offered.',
        'cookies_preference_title': 'Preference cookies',
        'cookies_preference_desc': 'Allow remembering information so that the user accesses the service with certain characteristics, such as the selected language.',
        'cookies_manage_title': 'Cookie management',
        'cookies_manage_desc': 'The user can configure their browser to accept or reject cookies. Most browsers automatically accept cookies, but you can modify this setting. However, if you decide to disable cookies, some features of the site may not be available.',
        'cookies_browsers_title': 'How to manage cookies in major browsers:',
        'cookies_contact_title': 'Contact',
        'cookies_contact_desc': 'For any questions about our cookie policy, you can contact us at:',        // PREMIO/BLOG PAGE
        'premio_page_title': 'Blog - CICTAEC',
        'premio_period_title': 'Period',
        'premio_award': 'Award',
        'premio_news': 'News',        'cookies_back_btn': '← Back to home',
        // PRIVACY PAGE
        'privacy_title': 'Privacy Policy',
        'privacy_intro': 'In compliance with the General Data Protection Regulation (GDPR) and the Organic Law on Data Protection (LOPD), we inform you about the processing of your personal data.',
        'privacy_responsible_title': 'Data Controller',
        'privacy_responsible_name': 'Responsible',
        'privacy_data_title': 'Personal data collected',
        'privacy_data_desc': 'Through the contact forms on our website, we may collect the following personal data:',
        'privacy_data_name': 'Name and surname',
        'privacy_data_email': 'Email address',
        'privacy_data_phone': 'Contact phone',
        'privacy_data_company': 'Company or organization',
        'privacy_data_message': 'Message or inquiry',
        'privacy_purpose_title': 'Purpose of processing',
        'privacy_purpose_desc': 'The personal data provided will be used to:',
        'privacy_purpose_1': 'Respond to your inquiries and information requests',
        'privacy_purpose_2': 'Provide commercial and tourist advisory services',
        'privacy_purpose_3': 'Send information about our services and activities (with your prior consent)',
        'privacy_purpose_4': 'Comply with legal and contractual obligations',
        'privacy_legal_title': 'Legal basis',
        'privacy_legal_desc': 'The processing of your personal data is based on your express consent when using our contact forms and on the execution of a contract or pre-contractual measures requested by you.',
        'privacy_conservation_title': 'Data retention',
        'privacy_conservation_desc': 'Your personal data will be retained for the time necessary to fulfill the purpose for which it was collected and, subsequently, during the limitation period of applicable legal obligations.',
        'privacy_rights_title': 'User rights',
        'privacy_rights_desc': 'You have the right to:',
        'privacy_rights_1': 'Access: Obtain information about whether we are processing your personal data',
        'privacy_rights_2': 'Rectification: Request correction of inaccurate or incomplete data',
        'privacy_rights_3': 'Erasure: Request deletion of your personal data',
        'privacy_rights_4': 'Restriction: Request restriction of processing of your data',
        'privacy_rights_5': 'Portability: Receive your data in a structured, commonly used format',
        'privacy_rights_6': 'Objection: Object to the processing of your personal data',
        'privacy_rights_access': 'Access',
        'privacy_rights_rectification': 'Rectification',
        'privacy_rights_deletion': 'Erasure',
        'privacy_rights_limitation': 'Restriction',
        'privacy_rights_portability': 'Portability',
        'privacy_rights_opposition': 'Objection',
        'privacy_rights_exercise': 'To exercise these rights, you can contact us at info@cictaec.es or at +34 664 413 231.',
        'privacy_security_title': 'Data security',
        'privacy_security_desc': 'CICTAEC has adopted the necessary technical and organizational measures to ensure the security and integrity of personal data, as well as to prevent loss, alteration or unauthorized access.',
        'privacy_changes_title': 'Policy modifications',
        'privacy_changes_desc': 'CICTAEC reserves the right to modify this privacy policy to adapt it to legislative or jurisprudential changes. We recommend periodically reviewing this page to be informed of any changes.',
        'privacy_back_btn': '← Back to home',
        'form_url': 'https://docs.google.com/forms/d/e/1FAIpQLScqEPD_uMeHBLZXmpucLE1a_TDyYZAjEGwem9Dfi8k9MheecA/viewform'
    },
    'ca': {
        'nav_home': 'INICI',
        'nav_about': 'Sobre nosaltres',
        'nav_areas': 'Àrees',
        'nav_premios': 'Blog',
        'nav_contact': 'Contacte',
        'hero_title': 'CICTAEC',
        'hero_subtitle': 'Cambra Internacional de Comerç i Turisme',
        'hero_slide_connect': 'CONNECTANT CONTINENTS',
        'hero_slide_bridge': 'EL TEU PONT AL MÓN',
        'hero_slide_3': 'CICTAEC',
        'about_title': 'Cambra Internacional de Comerç i Turisme Associació Equatoriana-Catalana',
        'about_description': 'CICTAEC és una organització de caràcter internacional que actua com a pont entre l\'Amèrica Llatina i Europa.',
        'founder_tag': 'SOBRE CICTAEC',
        'founder_quote': '"CICTAEC és una organització de caràcter internacional que actua com a pont entre l\'Amèrica Llatina<br>i Europa."',
        'founder_title': 'FUNDADORA',
        'mission_title': 'Missió',
        'mission_text': 'Ser un pont eficaç en la connexió internacional entre l\'Equador i Europa, promovent relacions comercials, facilitant oportunitats de negocis.',
        'vision_title': 'Visió',
        'vision_text': 'Ser una cambra de referència en la connexió internacional entre l\'Equador i Europa, relacionant sectors d\'importància com comerç, turisme i educació.',
        'areas_main_title': 'ÀREES',
        'area_1': 'COMERÇ',
        'area_2': 'CULTURA I TURISME',
        'area_3': 'ESPORT',
        'commerce_title': 'COMERÇ',
        'trad_prod_title': 'PRODUCTES TRADICIONALS',
        'trad_prod_desc': 'Connectem els mercats',
        'btn_more': 'VEURE MÉS DETALLS',
        'btn_info': 'SOL·LICITAR INFO',
        'btn_advisory': 'SOL·LICITAR ASSESSORAMENT',
        'btn_details': 'DETALLS',
        'btn_details_area': 'ANAR A LA SECCIÓ',
        'btn_form': 'FORMULARI DE CONTACTE',
        'ie_title': 'IMPORTACIÓ I EXPORTACIÓ',
        'ie_desc': 'Facilitem els processos logisticos',
        'products_section_title': 'PRODUCTES',
        'catalog_section_title': 'CATÀLEG',
        'btn_view_products': 'VEURE PRODUCTES',
        'tourism_subtitle': 'TURISME',
        'tourism_desc': 'Impulsem el turisme sostenible i el reconeixement de destinacions estratègiques en ambdós continents.',
        'cultural_subtitle': 'CULTURA',
        'cultural_desc': 'Preservem i difondrem les tradicions i l\'art de l\'Equador. La cultura és la nostra força per unir comunitats i impulsar el desenvolupament.',
        'sport_subtitle': 'PROMOVEM ESPORT',
        'sport_desc': 'Fomentem l\'intercanvi esportiu i la promoció d\'esdeveniments esportius entre l\'Equador i Europa, creant oportunitats de desenvolupament en l\'àmbit esportiu internacional.',
        'sport_page_title': 'ESPORT',
        'sport_clubs_title': 'CLUBS ASSOCIATS',
        'club1_name': 'BEISBOL4ALL',
        'club1_desc': 'Club especialitzat en beisbol amb programes de desenvolupament per a joves atletes. Fomenta l\'intercanvi esportiu i la formació de talent en el beisbol espanyol.',
        'club2_name': 'PENYA',
        'club2_desc': 'Club esportiu català amb tradició en múltiples disciplines. Enfocat en la promoció de l\'esport base i la cooperació internacional amb clubs d\'Amèrica Llatina.',
        'btn_visit_website': 'Visitar el lloc web',
        'sport_exchanges_title': 'INTERCANVIS ESPORTIUS',
        'sport_exchanges_desc': 'Facilitem l\'intercanvi d\'atletes, entrenadors i professionals de l\'esport entre l\'Equador i Europa, promovent la cooperació esportiva internacional i el desenvolupament de talent.',
        'sport_exchanges_item1': 'Programes d\'intercanvi per a atletes',
        'sport_exchanges_item2': 'Formació d\'entrenadors',
        'sport_exchanges_item3': 'Cooperació tècnica esportiva',
        'sport_events_title': 'ESDEVENIMENTS ESPORTIUS',
        'sport_events_desc': 'Organitzem i promocionem esdeveniments esportius que connecten l\'Equador amb Europa, creant oportunitats per a la participació internacional i el desenvolupament de l\'esport.',
        'sport_events_item1': 'Tornejos internacionals',
        'sport_events_item2': 'Competències bilaterals',
        'sport_events_item3': 'Esdeveniments esportius culturals',
        'sport_infrastructure_title': 'INFRAESTRUCTURA ESPORTIVA',
        'sport_infrastructure_desc': 'Donem suport al desenvolupament d\'infraestructura esportiva i la transferència de coneixements tècnics per millorar les instal·lacions i condicions d\'entrenament.',
        'sport_infrastructure_item1': 'Consultoria en instal·lacions esportives',
        'sport_infrastructure_item2': 'Equipament esportiu de qualitat',
        'sport_infrastructure_item3': 'Assessoria tècnica especialitzada',
        'sport_business_title': 'NEGOCIS ESPORTIUS',
        'sport_business_desc': 'Facilitem connexions comercials en el sector esportiu, incloent patrocinis, màrqueting esportiu i oportunitats d\'inversió en l\'àmbit esportiu internacional.',
        'sport_business_item1': 'Connexió amb patrocinadors',
        'sport_business_item2': 'Màrqueting esportiu internacional',
        'sport_business_item3': 'Oportunitats d\'inversió',
        'sport_contact_title': 'INTERESSAT EN COL·LABORAR?',
        'sport_contact_desc': 'Si desitges participar en els nostres programes esportius o tens una proposta de col·laboració, no dubtis en contactar-nos.',
        'btn_contact': 'CONTACTAR',
        'btn_back_home': 'Tornar a l\'inici',
        'contact_company_name': 'Cambra Internacional de Comerç i Turisme',
        'contact_section_title': 'CONTACTE',
        'address_label': 'Adreça:',
        'phone_label': 'Telèfon:',
        'footer_copy': '© 2026 CICTAEC - Cambra Internacional de Comerç i Turisme. Tots els drets reservats.',
        'prod_1_title': 'OLI',
        'prod_2_title': 'FRUITES',
        'prod_3_title': 'TÈXTIL',
        'prod_4_title': 'PERNIL',
        'prod_5_title': 'PEIX',        'prod_6_title': 'CACAU',        'prod_7_title': 'BEGUDES ALCOHÒLIQUES',
        'prod_8_title': 'CEREALS',
        'prod_9_title': 'VERDURES',
        'prod_harina_title': 'FARINA',
        'prod_harina_desc': 'Farina de blat d\'alta qualitat per a la indústria de la flequería i la pastisseria, ideal per a l\'exportació internacional.',
        'prod_pasta_title': 'PASTA',
        'prod_pasta_desc': 'Pasta italiana d\'alta qualitat elaborada amb blat dur, perfecta per a la gastronomia internacional i l\'exportació.',
        'prod_patatas_fritas_title': 'PATATES FREGIDES',
        'prod_patatas_fritas_desc': 'Patates fregides cruixents de qualitat superior, elaborades amb les millors patates europees per a l\'exportació.',
        'prod_papas_dauphine_title': 'PATATES DAUPHINE',
        'prod_papas_dauphine_desc': 'Patates dauphine de cuina francesa, barreja perfecta de puré de patata i pasta choux, llestes per a l\'exportació.',
        'prod_vino_title': 'VI',
        'prod_vino_desc': 'Vins selectes d\'alta qualitat, ideals per a l\'exportació a mercats internacionals exigents.',
        'prod_champagne_title': 'XAMPANY',
        'prod_champagne_desc': 'Xampany premium d\'origen europeu, perfecte per a celebracions i esdeveniments especials de luxe.',
        'prod_1_desc': 'Oli d\'alta qualitat provinent de l\'Equador, ideal per a l\'exportació a mercats internacionals.',
        'prod_2_desc': 'Fruites fresques i fruites seques de la millor qualitat, cultivades a les terres equatorianes.',
        'prod_aceite_oliva_intenso': 'OLI D\'OLIVA INTENS',
        'prod_aceite_oliva_intenso_desc': 'Oli d\'oliva intens d\'alta qualitat, ideal per a l\'exportació a mercats internacionals.',
        'prod_3_desc': 'Productes tèxtils artesanals d\'alta qualitat, representant la tradició equatoriana.',
        'prod_banana_title': 'BANANA',
        'prod_banana_desc': 'Banana equatoriana d\'exportació, reconeguda mundialment pel seu sabor dolç i textura perfecta.',
        'prod_pitaya_title': 'PITAYA',
        'prod_pitaya_desc': 'Pitaya o fruita del drac, exòtica i nutritiva, cultivada a les terres tropicals de l\'Equador.',
        'prod_4_desc': 'Pernil curat de qualitat excel·lent, preparat amb mètodes tradicionals.',
        'prod_5_desc': 'Peix fresc i marisc de les costes del Pacífic equatorià.',
        'prod_6_desc': 'Cacau equatorià de fina aroma, reconegut mundialment per la seva qualitat excepcional i sabor únic.',
        'prod_atun_title': 'TONYINA',
        'prod_atun_desc': 'Tonyina fresca de les costes del Pacífic equatorià, ideal per a la gastronomia internacional.',
        'prod_camaron_title': 'GAMBA',
        'prod_camaron_desc': 'Gamba equatoriana de primera qualitat, reconeguda pel seu sabor i frescor excepcionals.',
        'prod_albacora_title': 'ALBACORA',
        'prod_albacora_desc': 'Albacora d\'aigües profundes del Pacífic, apreciada per la seva textura ferma i sabor delicat.',        'prod_aceite_virgen': 'OLI VERGE EXTRA',
        'prod_aceite_virgen_desc': 'Oli verge extra de primera premsa en fred, amb certificació de qualitat premium per a mercats internacionals.',        'products_page_title': 'Els Nostres Productes',
        'badge_export': 'Exportació',
        'badge_import': 'Importació',
        'error_title': 'Pàgina no trobada',
        'error_message': 'Ho sentim, la pàgina que cerques no existeix o ha estat moguda. Et convidem a tornar a la pàgina principal o explorar els nostres productes i serveis.',
        'error_btn_home': 'Tornar a l\'inici',
        'error_btn_products': 'Veure productes',
        // COOKIES PAGE
        'cookies_title': 'Política de Cookies',
        'cookies_intro': 'Aquest lloc web utilitza cookies tècniques necessàries per al seu funcionament i per millorar l\'experiència de navegació de l\'usuari.',
        'cookies_what_title': 'Què són les cookies?',
        'cookies_what_desc': 'Les cookies són petits fitxers de text que s\'emmagatzemen al navegador de l\'usuari quan visita un lloc web. Permeten que el lloc recordi informació sobre la vostra visita, com el vostre idioma preferit i altres opcions, cosa que pot facilitar la vostra propera visita i fer que el lloc us sigui més útil.',
        'cookies_types_title': 'Tipus de cookies que utilitzem',
        'cookies_technical_title': 'Cookies tècniques (necessàries)',
        'cookies_technical_desc': 'Són imprescindibles per al correcte funcionament del lloc web. Permeten la navegació i l\'ús de les diferents opcions o serveis que ofereix.',
        'cookies_preference_title': 'Cookies de preferències',
        'cookies_preference_desc': 'Permeten recordar informació perquè l\'usuari accedeixi al servei amb determinades característiques, com l\'idioma seleccionat.',
        'cookies_manage_title': 'Gestió de cookies',
        'cookies_manage_desc': 'L\'usuari pot configurar el seu navegador per acceptar o rebutjar cookies. La majoria dels navegadors accepten cookies automàticament, però podeu modificar aquesta configuració. No obstant això, si decidiu desactivar les cookies, és possible que algunes funcionalitats del lloc no estiguin disponibles.',
        'cookies_browsers_title': 'Com gestionar cookies als principals navegadors:',
        'cookies_contact_title': 'Contacte',
        'cookies_contact_desc': 'Per a qualsevol consulta sobre la nostra política de cookies, podeu contactar-nos a:',        // PREMIO/BLOG PAGE
        'premio_page_title': 'Blog - CICTAEC',
        'premio_period_title': 'Període',
        'premio_award': 'Premi',
        'premio_news': 'Notícia',        'cookies_back_btn': '← Tornar a l\'inici',
        // PRIVACY PAGE
        'privacy_title': 'Política de Privacitat',
        'privacy_intro': 'En compliment del Reglament General de Protecció de Dades (RGPD) i la Llei Orgànica de Protecció de Dades (LOPD), us informem sobre el tractament de les vostres dades personals.',
        'privacy_responsible_title': 'Responsable del tractament',
        'privacy_responsible_name': 'Responsable',
        'privacy_data_title': 'Dades personals recollides',
        'privacy_data_desc': 'A través dels formularis de contacte del nostre lloc web, podem recopilar les següents dades personals:',
        'privacy_data_name': 'Nom i cognoms',
        'privacy_data_email': 'Adreça de correu electrònic',
        'privacy_data_phone': 'Telèfon de contacte',
        'privacy_data_company': 'Empresa o organització',
        'privacy_data_message': 'Missatge o consulta',
        'privacy_purpose_title': 'Finalitat del tractament',
        'privacy_purpose_desc': 'Les dades personals proporcionades seran utilitzades per:',
        'privacy_purpose_1': 'Respondre a les vostres consultes i sol·licituds d\'informació',
        'privacy_purpose_2': 'Proporcionar serveis d\'assessorament comercial i turístic',
        'privacy_purpose_3': 'Enviar informació sobre els nostres serveis i activitats (amb el vostre consentiment previ)',
        'privacy_purpose_4': 'Complir amb obligacions legals i contractuals',
        'privacy_legal_title': 'Base legal',
        'privacy_legal_desc': 'El tractament de les vostres dades personals es basa en el vostre consentiment exprés en utilitzar els nostres formularis de contacte i en l\'execució d\'un contracte o mesures precontractuals sol·licitades per vosaltres.',
        'privacy_conservation_title': 'Conservació de dades',
        'privacy_conservation_desc': 'Les vostres dades personals seran conservades durant el temps necessari per complir amb la finalitat per a la qual van ser recollides i, posteriorment, durant el període de prescripció de les obligacions legals aplicables.',
        'privacy_rights_title': 'Drets de l\'usuari',
        'privacy_rights_desc': 'Teniu dret a:',
        'privacy_rights_1': 'Accés: Obtenir informació sobre si estem tractant les vostres dades personals',
        'privacy_rights_2': 'Rectificació: Sol·licitar la correcció de dades inexactes o incompletes',
        'privacy_rights_3': 'Supressió: Sol·licitar l\'eliminació de les vostres dades personals',
        'privacy_rights_4': 'Limitació: Sol·licitar la limitació del tractament de les vostres dades',
        'privacy_rights_5': 'Portabilitat: Rebre les vostres dades en un format estructurat i d\'ús comú',
        'privacy_rights_6': 'Oposició: Oposar-vos al tractament de les vostres dades personals',
        'privacy_rights_access': 'Accés',
        'privacy_rights_rectification': 'Rectificació',
        'privacy_rights_deletion': 'Supressió',
        'privacy_rights_limitation': 'Limitació',
        'privacy_rights_portability': 'Portabilitat',
        'privacy_rights_opposition': 'Oposició',
        'privacy_rights_exercise': 'Per exercir aquests drets, podeu contactar-nos a info@cictaec.es o al +34 664 413 231.',
        'privacy_security_title': 'Seguretat de les dades',
        'privacy_security_desc': 'CICTAEC ha adoptat les mesures tècniques i organitzatives necessàries per garantir la seguretat i integritat de les dades personals, així com per evitar la seva pèrdua, alteració o accés no autoritzat.',
        'privacy_changes_title': 'Modificacions de la política',
        'privacy_changes_desc': 'CICTAEC es reserva el dret de modificar aquesta política de privacitat per adaptar-la a canvis legislatius o jurisprudencials. Us recomanem revisar periòdicament aquesta pàgina per estar informat de qualsevol canvi.',
        'privacy_back_btn': '← Tornar a l\'inici',
        'form_url': 'https://docs.google.com/forms/d/e/1FAIpQLSeuPu_ceclsak6l1MelMbZuSp5_WQ3Oscagp_49upE67mSDhg/viewform'
    }
};

// ==========================================
// 3. FUNCIÓN DE CAMBIO DE IDIOMA
// ==========================================
function setLang(lang) {
    const elements = document.querySelectorAll('[data-key]');
    elements.forEach(el => {
        const key = el.getAttribute('data-key');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });

    const currentFlag = document.getElementById('current-flag');
    const currentLangText = document.getElementById('current-lang-text');
    
    if (currentFlag) currentFlag.src = `images/flag_${lang}.png`;
    if (currentLangText) currentLangText.innerText = lang.toUpperCase();

    // Changer l'URL du formulaire de contact selon la langue
    const contactFormLink = document.getElementById('contact-form-link');
    if (contactFormLink && translations[lang] && translations[lang]['form_url']) {
        contactFormLink.href = translations[lang]['form_url'];
    }

    localStorage.setItem('preferredLang', lang);
}

// ==========================================
// 4. FONCTION DE REDIRECTION VERS FORMULAIRE
// ==========================================
function redirectToForm() {
    const savedLang = localStorage.getItem('preferredLang') || 'es';
    const formUrl = translations[savedLang] && translations[savedLang]['form_url'] 
        ? translations[savedLang]['form_url'] 
        : 'https://forms.gle/5951nVBJNCh4sBi78';
    window.open(formUrl, '_blank');
}

// ==========================================
// 5. INICIALIZACIÓN
// ==========================================
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('preferredLang') || 'es';
    setLang(savedLang);
    showSlide(0);

    // --- EFECTO ZOOM PRODUCTOS ---
    const productItems = document.querySelectorAll('.product-item');
    productItems.forEach(item => {
        item.style.transition = 'transform 0.3s ease, box-shadow 0.3s ease';
        item.addEventListener('mouseenter', () => {
            item.style.transform = 'scale(1.05)';
            item.style.boxShadow = '0 10px 20px rgba(0,0,0,0.15)';
        });
        item.addEventListener('mouseleave', () => {
            item.style.transform = 'scale(1)';
            item.style.boxShadow = '0 2px 8px rgba(0, 0, 0, 0.1)';
        });
    });
});

// --- ANIMATION DES TITRES AU SCROLL ---
const observerOptions = {
    threshold: 0.2 
};

const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
        if (entry.isIntersecting) {
            entry.target.classList.add('active');
        }
    });
}, observerOptions);

const titlesToAnimate = document.querySelectorAll('.reveal-title');
titlesToAnimate.forEach(title => observer.observe(title));

// --- ANIMATION DES SECTIONS AU SCROLL ---
const sectionObserver = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
        if (entry.isIntersecting) {
            entry.target.classList.add('visible');
        }
    });
}, { threshold: 0.1 });

const elementsToAnimate = document.querySelectorAll('.animate-on-scroll, .animate-on-scroll-delay');
elementsToAnimate.forEach(element => sectionObserver.observe(element));

// --- EFFET PARALLAX SUBTIL POUR LE FOND ---
window.addEventListener('scroll', function() {
    const backgrounds = document.querySelectorAll('.index-background');
    backgrounds.forEach(bg => {
        const scrolled = window.pageYOffset;
        const rect = bg.getBoundingClientRect();
        const bgTop = rect.top + scrolled;
        const offset = (scrolled - bgTop) * 0.3;
        bg.style.backgroundPositionY = `calc(50% - ${offset}px)`;
    });
});